### ISSUE TITLE
Invalid prop: type check failed for prop "closable". Expected Boolean, got String with value "true".

### ISSUE THREAD

**Issue by papakay** [mengdu/m-message#11]
I have a block of code as below:

```
this.$toast.error({
                message: "Something has gone wrong.",
                duration: process.env.TOAST_DURATION,
                showClose: process.env.TOAST_SHOW_CLOSE,
                zIndex: 2000
              })
```
I get the following error in the console.

Invalid prop: type check failed for prop "closable". Expected Boolean, got String with value "true".

![Screenshot 2020-03-24 at 07 44 55](https://user-images.githubusercontent.com/5013738/77396241-ac895680-6da3-11ea-8fb0-84cbbc2a9747.png)

**Comment by mengdu** [comment]
It needs to be clear that the values on `process.env.[key]` are of string type, but the `showClose` must provide a Boolean value.

**Comment by mengdu** [comment]
process.env.TOAST_SHOW_CLOSE value is `"true"`

Your should:
```js
this.$toast.error({
                message: "Something has gone wrong.",
                duration: process.env.TOAST_DURATION,
                showClose: process.env.TOAST_SHOW_CLOSE === "true",
                zIndex: 2000
              })
```

**Comment by papakay** [comment]
The value of process.env.TOAST_SHOW_CLOSE is `true` and not `"true"`

![Screenshot 2020-03-24 at 08 30 01](https://user-images.githubusercontent.com/5013738/77399454-c9c12380-6da9-11ea-9f80-964b7764cb80.png)

**Comment by papakay** [comment]
I've also tried

```
this.$toast.error({
                message: "Something has gone wrong.",
                duration: process.env.TOAST_DURATION,
                showClose: true,
                zIndex: 2000
              })
```

And still get the same error message.

**Comment by mengdu** [comment]
You can check whether the following types match：

```ts
export interface MessageOptions {
  title?: string;
  message: string;
  type?: 'info' | 'success' | 'error' | 'warning' | 'loading';
  isCollapsed: boolean;
  width?: string;
  showClose: boolean;
  className?: string;
  wrapperClassName?: string;
  supportHTML?: boolean;
  onClose?: () => void;
  duration: number | 3000;
  zIndex: number | 1010;
  iconImg?: string;
  hasMask: boolean;
  position?: 'top-left' | 'top-center' | 'top-right' | 'center' | 'bottom-left' | 'bottom-center' | 'bottom-right'
}
```

**Comment by mengdu** [comment]
It is worth noting that the key set on `process.env` is converted to a string type.

**Comment by papakay** [comment]
> It is worth noting that the key set on `process.env` is converted to a string type.

If this is correct, then the duration env parameter for TOAST_DURATION should also not work.

Please what do you think about this?

**Comment by papakay** [comment]
Thank you so much @mengdu  for your time and also for pointing me in the right direction.

I think ` showClose: process.env.TOAST_SHOW_CLOSE === "true",` will work.

Thank you a lot
