### ISSUE TITLE
Disable folding option

### ISSUE THREAD

**Issue by mas-iota** [mengdu/m-message#15]
Hi can you add an option to disable message folding entirely? something like

`   { collapsable: false }
`

**Comment by mengdu** [comment]
[options](https://github.com/mengdu/m-message#options)

```
options.isCollapsed
```

**Comment by mas-iota** [comment]
@mengdu isCollapsed will initiate the notification folded/unfolded, but still, the user would be able to see the arrow and collapse the notification.

**Comment by mengdu** [comment]
```js
this.$message({
        type: this.type,
        message: this.msg,
        showClose: true,
        position: this.position
      })
```
[Demo](https://github.com/mengdu/m-message/blob/master/examples/docs/index.md)

**Comment by mas-iota** [comment]
showClose is to show/hide the close option, what I mean is the arrow (folding/unfolding) options. Please see below screenshot:

![Screenshot](https://i.imgur.com/6ppu3BI.png)

I need to hide it.

**Comment by omaralsoudanii** [comment]
@mas-iota 
Have you tried turning it off and on again?

If that doesn't work, then feel free to open a PR because it's not my problem if you don't understand JabbaScript.

**Comment by mas-iota** [comment]
@omaralsoudanii 
I just tried to restart the browser it won't work, I even disabled and re-enabled JabbaScript, no luck :(

**Comment by mengdu** [comment]
@mas-iota Oh, I see. There is no such setting for the time being.
Temporary processing, you can hide it with style.
