### ISSUE TITLE
Close button does not hide when duration = -1

### ISSUE THREAD

**Issue by robertmylne** [mengdu/m-message#22]
When `duration: -1` then the variable `showClose: false` does not hide the close button.

**Comment by mengdu** [comment]
When manual closing is required, the close button will be displayed, and showclose = false will be invalid.

**Comment by robertmylne** [comment]
Why? 

My use case uses showHTML to show a button called “refresh” inside the message box which reloads the page. I do not want it to be dismissable as I want it to display until the user presses “refresh”. It should allow overriding of the close button when the option is hard coded. The restriction therefore requires the developer the put a “display: none” in css to hide the close button.

**Comment by robertmylne** [comment]
![9F0DECED-F33A-4FE8-93E7-541A7E6CFC2D](https://user-images.githubusercontent.com/10385217/113876253-e84e5d00-97fa-11eb-8ac0-89bd480ada5b.jpeg)

here is the example of what I made by using css to hide the close button, but it would be nice to allow it.

**Comment by mengdu** [comment]
Oh, I get it. I will update the next version.

**Comment by mengdu** [comment]
I'm already in v4 0.1 has been modified.
