### ISSUE TITLE
There are multiple modules with names that only differ in casing.

### ISSUE THREAD

**Issue by papakay** [mengdu/m-message#3]
I really commend the great work done with this plugin.

Please i got an error on the console while running `npm run dev`

```
There are multiple modules with names that only differ in casing.                            friendly-errors 22:21:09
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Library/WebServer/Documents/ngcareers/node_modules/Vue/dist/vue.runtime.esm.js
    Used by 1 module(s), i. e.
    /Library/WebServer/Documents/ngcareers/node_modules/vue-m-message/dist/index.js
```

I guess the fix is by changing `require("Vue")` to `require("vue")` and `define("Message",["Vue"],e)` to `define("Message",["vue"],e)`

Please can you kindly help look into this.

Thank you.

**Comment by mengdu** [comment]
Oh, well, I'll fix it at work the day after tomorrow.


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
