### ISSUE TITLE
HTML in message

### ISSUE THREAD

**Issue by jdhines** [mengdu/m-message#4]
If I wanted to pass in a message with some HTML, for example, an anchor tag, how would I do that? If I pass just a string, obviously it gets escaped and the HTML shows up in the toast.

Example: I would like to be able to do this:

```
this.$message.error({
  message: `Oops. Please contact <a href="mailto:support@co.com">support@co.com</a>`
})
```

**Comment by mengdu** [comment]
Well, HTML messages are not currently supported; you'll consider adding support for this feature later.

**Comment by mengdu** [comment]
Use `options.supportHTML` for support HTML on `v2.0.0`
