### ISSUE TITLE
CDN Global

### ISSUE THREAD

**Issue by amchconsult** [mengdu/m-message#42]
please, Can you give an example with CDN?

I am using:

```
Vue.use(window.VueMMessage);

handleMessage: function() {
        this.$message({
            type: "info",
            message: "this is a test",
            showClose: true,
            position: "top-center",
            hasMask: false,
        })
    },
```
And I get this error:

[Vue warn]: Error in v-on handler: "TypeError: this.message is not a function"

(found in <Root>)
warn @ vue.js:634
logError @ vue.js:1902
globalHandleError @ vue.js:1897
handleError @ vue.js:1857
invokeWithErrorHandling @ vue.js:1880
invoker @ vue.js:2197
original._wrapper @ vue.js:7591
vue.js:1906 TypeError: this.message is not a function
    at Vue.handleMessage (index.html:130:14)
    at click (eval at createFunction (vue.js:11698:14), <anonymous>:3:603)
    at invokeWithErrorHandling (vue.js:1872:28)
    at HTMLButtonElement.invoker (vue.js:2197:16)
    at HTMLButtonElement.original._wrapper (vue.js:7591:27)

Thank you

**Comment by mengdu** [comment]
Just do it:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Hello</title>
  <link rel="stylesheet" href="https://unpkg.com/vue-m-message@3.1.0/dist/index.css">
  <!-- vue 2.x must -->
  <script src="https://cdn.bootcdn.net/ajax/libs/vue/2.6.9/vue.min.js"></script>
  <!-- message lib -->
  <script src="https://unpkg.com/vue-m-message@3.1.0/dist/index.umd.js"></script>
</head>
<body>
<script>
window.onload = function () {
  VueMMessage.default.success('Hello')
}
</script>
</body>
</html>
```

**Comment by amchconsult** [comment]
thank you, it works perfect.

I translate your help to this:

Vue.use(window.VueMMessage.default);

and now it works

Thank you again
