### ISSUE TITLE
vue3 使用报错,有大佬知道怎么解决吗?

### ISSUE THREAD

**Issue by sengoku-f** [mengdu/m-message#47]
```
this.$message.success('This is a success message')
```

`Uncaught TypeError: Cannot read properties of undefined (reading 'success')`

**Comment by mengdu** [comment]
如果你是这样全局注册的，访问 `this.$mmessage` 才对。

```js
import Message from 'vue-m-message'
import App from './App.vue'
const app = createApp(App)
app.use(Message)
```

或者你 `app.use(Message, options: { name: 'message'})` 试试。

**Comment by sengoku-f** [comment]
> 如果你是这样全局注册的，访问 `this.$mmessage` 才对。
> 
> ```js
> import Message from 'vue-m-message'
> import App from './App.vue'
> const app = createApp(App)
> app.use(Message)
> ```
> 
> 或者你 `app.use(Message, options: { name: 'message'})` 试试。

我原来是这样注册的
```
import { createApp } from 'vue'
import App from './App.vue'
import Message from 'vue-m-message'
import 'vue-m-message/dist/style.css'

const app = createApp(App)
app.use(Message)

app.mount("#app");
```
发现改为这样`app.config.globalProperties.$message = Message`就能正常用了
`app.use(Message, options: { name: 'message'})`这样显示语法有问题
