### ISSUE TITLE
Global settings?

### ISSUE THREAD

**Issue by tpaksu** [mengdu/m-message#9]
Hello, 

First of all, thanks for that beautiful plugin.

Can we have a global settings object? Like when we write:

```javascript
Message.globals.config.position = 'bottom-right';
```

All the calls to `Message.{type}` would use `bottom-right` positioning.

**Comment by mengdu** [comment]
Oh, not for now.

**Comment by git-chenjiqing** [comment]
缺少全局设置真的很惨尼

**Comment by mengdu** [comment]
是的，改天有空我加个上来
